name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10.x'
      - uses: actions/checkout@v3
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: '1.1.13'
      - name: Run
        run: poetry run make ci
